default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Indenseo_development


test:
  <<: *default
  database: Indenseo_test

#
production:
  <<: *default
  database: Indenseo_production
  username: Indenseo
  password: <%= ENV['BROWN-BANANAS_DATABASE_PASSWORD'] %>
